/* Generated by tools/build-webp.py. Editor export may replace this file. */
window.SETTINGS = {
  "bookCols": 2,
  "bookRows": 3
};

window.STICKERS = [
  {
    "id": "001",
    "webp": "webp/001.webp",
    "label": "",
    "url": "",
    "rank": 1,
    "canvas": {
      "x": 69.0,
      "y": 84.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "002",
    "webp": "webp/002.webp",
    "label": "",
    "url": "",
    "rank": 2,
    "canvas": {
      "x": 317.0,
      "y": 89.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "003",
    "webp": "webp/003.webp",
    "label": "",
    "url": "",
    "rank": 3,
    "canvas": {
      "x": 550.0,
      "y": 89.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "004",
    "webp": "webp/004.webp",
    "label": "",
    "url": "",
    "rank": 4,
    "canvas": {
      "x": 765.0,
      "y": 68.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "005",
    "webp": "webp/005.webp",
    "label": "",
    "url": "",
    "rank": 5,
    "canvas": {
      "x": 980.0,
      "y": 64.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "006",
    "webp": "webp/006.webp",
    "label": "",
    "url": "",
    "rank": 6,
    "canvas": {
      "x": 1241.0,
      "y": 75.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "007",
    "webp": "webp/007.webp",
    "label": "",
    "url": "",
    "rank": 7,
    "canvas": {
      "x": 1454.0,
      "y": 62.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "008",
    "webp": "webp/008.webp",
    "label": "",
    "url": "",
    "rank": 8,
    "canvas": {
      "x": 1696.0,
      "y": 67.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "009",
    "webp": "webp/009.webp",
    "label": "",
    "url": "",
    "rank": 9,
    "canvas": {
      "x": 1924.0,
      "y": 65.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "010",
    "webp": "webp/010.webp",
    "label": "",
    "url": "",
    "rank": 10,
    "canvas": {
      "x": 2167.0,
      "y": 69.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "011",
    "webp": "webp/011.webp",
    "label": "",
    "url": "",
    "rank": 11,
    "canvas": {
      "x": 2387.0,
      "y": 70.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "012",
    "webp": "webp/012.webp",
    "label": "",
    "url": "",
    "rank": 12,
    "canvas": {
      "x": 2593.0,
      "y": 68.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "013",
    "webp": "webp/013.webp",
    "label": "",
    "url": "",
    "rank": 13,
    "canvas": {
      "x": 2844.0,
      "y": 72.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "014",
    "webp": "webp/014.webp",
    "label": "",
    "url": "",
    "rank": 14,
    "canvas": {
      "x": 3078.0,
      "y": 86.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "015",
    "webp": "webp/015.webp",
    "label": "",
    "url": "",
    "rank": 15,
    "canvas": {
      "x": 3280.0,
      "y": 63.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "016",
    "webp": "webp/016.webp",
    "label": "",
    "url": "",
    "rank": 16,
    "canvas": {
      "x": 3526.0,
      "y": 87.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "017",
    "webp": "webp/017.webp",
    "label": "",
    "url": "",
    "rank": 17,
    "canvas": {
      "x": 3750.0,
      "y": 70.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "018",
    "webp": "webp/018.webp",
    "label": "",
    "url": "",
    "rank": 18,
    "canvas": {
      "x": 85.0,
      "y": 333.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "019",
    "webp": "webp/019.webp",
    "label": "",
    "url": "",
    "rank": 19,
    "canvas": {
      "x": 323.0,
      "y": 330.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "020",
    "webp": "webp/020.webp",
    "label": "",
    "url": "",
    "rank": 20,
    "canvas": {
      "x": 559.0,
      "y": 336.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "021",
    "webp": "webp/021.webp",
    "label": "",
    "url": "",
    "rank": 21,
    "canvas": {
      "x": 766.0,
      "y": 356.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "022",
    "webp": "webp/022.webp",
    "label": "",
    "url": "",
    "rank": 22,
    "canvas": {
      "x": 1016.0,
      "y": 366.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "023",
    "webp": "webp/023.webp",
    "label": "",
    "url": "",
    "rank": 23,
    "canvas": {
      "x": 1226.0,
      "y": 346.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "024",
    "webp": "webp/024.webp",
    "label": "",
    "url": "",
    "rank": 24,
    "canvas": {
      "x": 1469.0,
      "y": 364.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "025",
    "webp": "webp/025.webp",
    "label": "",
    "url": "",
    "rank": 25,
    "canvas": {
      "x": 1697.0,
      "y": 350.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "026",
    "webp": "webp/026.webp",
    "label": "",
    "url": "",
    "rank": 26,
    "canvas": {
      "x": 1928.0,
      "y": 353.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "027",
    "webp": "webp/027.webp",
    "label": "",
    "url": "",
    "rank": 27,
    "canvas": {
      "x": 2161.0,
      "y": 352.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "028",
    "webp": "webp/028.webp",
    "label": "",
    "url": "",
    "rank": 28,
    "canvas": {
      "x": 2399.0,
      "y": 346.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "029",
    "webp": "webp/029.webp",
    "label": "",
    "url": "",
    "rank": 29,
    "canvas": {
      "x": 2626.0,
      "y": 349.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "030",
    "webp": "webp/030.webp",
    "label": "",
    "url": "",
    "rank": 30,
    "canvas": {
      "x": 2858.0,
      "y": 363.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "031",
    "webp": "webp/031.webp",
    "label": "",
    "url": "",
    "rank": 31,
    "canvas": {
      "x": 3051.0,
      "y": 363.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "032",
    "webp": "webp/032.webp",
    "label": "",
    "url": "",
    "rank": 32,
    "canvas": {
      "x": 3313.0,
      "y": 363.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "033",
    "webp": "webp/033.webp",
    "label": "",
    "url": "",
    "rank": 33,
    "canvas": {
      "x": 3511.0,
      "y": 336.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "034",
    "webp": "webp/034.webp",
    "label": "",
    "url": "",
    "rank": 34,
    "canvas": {
      "x": 3751.0,
      "y": 366.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "035",
    "webp": "webp/035.webp",
    "label": "",
    "url": "",
    "rank": 35,
    "canvas": {
      "x": 80.0,
      "y": 610.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "036",
    "webp": "webp/036.webp",
    "label": "",
    "url": "",
    "rank": 36,
    "canvas": {
      "x": 317.0,
      "y": 603.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "037",
    "webp": "webp/037.webp",
    "label": "",
    "url": "",
    "rank": 37,
    "canvas": {
      "x": 540.0,
      "y": 633.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "038",
    "webp": "webp/038.webp",
    "label": "",
    "url": "",
    "rank": 38,
    "canvas": {
      "x": 789.0,
      "y": 603.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "039",
    "webp": "webp/039.webp",
    "label": "",
    "url": "",
    "rank": 39,
    "canvas": {
      "x": 996.0,
      "y": 622.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "040",
    "webp": "webp/040.webp",
    "label": "",
    "url": "",
    "rank": 40,
    "canvas": {
      "x": 1220.0,
      "y": 610.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "041",
    "webp": "webp/041.webp",
    "label": "",
    "url": "",
    "rank": 41,
    "canvas": {
      "x": 1446.0,
      "y": 609.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "042",
    "webp": "webp/042.webp",
    "label": "",
    "url": "",
    "rank": 42,
    "canvas": {
      "x": 1704.0,
      "y": 636.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "043",
    "webp": "webp/043.webp",
    "label": "",
    "url": "",
    "rank": 43,
    "canvas": {
      "x": 1936.0,
      "y": 603.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "044",
    "webp": "webp/044.webp",
    "label": "",
    "url": "",
    "rank": 44,
    "canvas": {
      "x": 2141.0,
      "y": 623.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "045",
    "webp": "webp/045.webp",
    "label": "",
    "url": "",
    "rank": 45,
    "canvas": {
      "x": 2395.0,
      "y": 634.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "046",
    "webp": "webp/046.webp",
    "label": "",
    "url": "",
    "rank": 46,
    "canvas": {
      "x": 2592.0,
      "y": 618.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "047",
    "webp": "webp/047.webp",
    "label": "",
    "url": "",
    "rank": 47,
    "canvas": {
      "x": 2829.0,
      "y": 617.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "048",
    "webp": "webp/048.webp",
    "label": "",
    "url": "",
    "rank": 48,
    "canvas": {
      "x": 3082.0,
      "y": 621.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "049",
    "webp": "webp/049.webp",
    "label": "",
    "url": "",
    "rank": 49,
    "canvas": {
      "x": 3293.0,
      "y": 624.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "050",
    "webp": "webp/050.webp",
    "label": "",
    "url": "",
    "rank": 50,
    "canvas": {
      "x": 3520.0,
      "y": 638.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "051",
    "webp": "webp/051.webp",
    "label": "",
    "url": "",
    "rank": 51,
    "canvas": {
      "x": 3763.0,
      "y": 617.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "052",
    "webp": "webp/052.webp",
    "label": "",
    "url": "",
    "rank": 52,
    "canvas": {
      "x": 70.0,
      "y": 883.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "053",
    "webp": "webp/053.webp",
    "label": "",
    "url": "",
    "rank": 53,
    "canvas": {
      "x": 315.0,
      "y": 872.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "054",
    "webp": "webp/054.webp",
    "label": "",
    "url": "",
    "rank": 54,
    "canvas": {
      "x": 551.0,
      "y": 873.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "055",
    "webp": "webp/055.webp",
    "label": "",
    "url": "",
    "rank": 55,
    "canvas": {
      "x": 777.0,
      "y": 879.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "056",
    "webp": "webp/056.webp",
    "label": "",
    "url": "",
    "rank": 56,
    "canvas": {
      "x": 991.0,
      "y": 878.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "057",
    "webp": "webp/057.webp",
    "label": "",
    "url": "",
    "rank": 57,
    "canvas": {
      "x": 1238.0,
      "y": 883.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "058",
    "webp": "webp/058.webp",
    "label": "",
    "url": "",
    "rank": 58,
    "canvas": {
      "x": 1451.0,
      "y": 889.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "059",
    "webp": "webp/059.webp",
    "label": "",
    "url": "",
    "rank": 59,
    "canvas": {
      "x": 1697.0,
      "y": 891.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "060",
    "webp": "webp/060.webp",
    "label": "",
    "url": "",
    "rank": 60,
    "canvas": {
      "x": 1917.0,
      "y": 896.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "061",
    "webp": "webp/061.webp",
    "label": "",
    "url": "",
    "rank": 61,
    "canvas": {
      "x": 2170.0,
      "y": 902.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "062",
    "webp": "webp/062.webp",
    "label": "",
    "url": "",
    "rank": 62,
    "canvas": {
      "x": 2375.0,
      "y": 906.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "063",
    "webp": "webp/063.webp",
    "label": "",
    "url": "",
    "rank": 63,
    "canvas": {
      "x": 2615.0,
      "y": 873.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "064",
    "webp": "webp/064.webp",
    "label": "",
    "url": "",
    "rank": 64,
    "canvas": {
      "x": 2828.0,
      "y": 898.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "065",
    "webp": "webp/065.webp",
    "label": "",
    "url": "",
    "rank": 65,
    "canvas": {
      "x": 3067.0,
      "y": 904.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "066",
    "webp": "webp/066.webp",
    "label": "",
    "url": "",
    "rank": 66,
    "canvas": {
      "x": 3285.0,
      "y": 891.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "067",
    "webp": "webp/067.webp",
    "label": "",
    "url": "",
    "rank": 67,
    "canvas": {
      "x": 3516.0,
      "y": 882.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "068",
    "webp": "webp/068.webp",
    "label": "",
    "url": "",
    "rank": 68,
    "canvas": {
      "x": 3760.0,
      "y": 892.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "069",
    "webp": "webp/069.webp",
    "label": "",
    "url": "",
    "rank": 69,
    "canvas": {
      "x": 75.0,
      "y": 1154.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "070",
    "webp": "webp/070.webp",
    "label": "",
    "url": "",
    "rank": 70,
    "canvas": {
      "x": 320.0,
      "y": 1155.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "071",
    "webp": "webp/071.webp",
    "label": "",
    "url": "",
    "rank": 71,
    "canvas": {
      "x": 535.0,
      "y": 1174.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "072",
    "webp": "webp/072.webp",
    "label": "",
    "url": "",
    "rank": 72,
    "canvas": {
      "x": 750.0,
      "y": 1145.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "073",
    "webp": "webp/073.webp",
    "label": "",
    "url": "",
    "rank": 73,
    "canvas": {
      "x": 1004.0,
      "y": 1174.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "074",
    "webp": "webp/074.webp",
    "label": "",
    "url": "",
    "rank": 74,
    "canvas": {
      "x": 1224.0,
      "y": 1157.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "075",
    "webp": "webp/075.webp",
    "label": "",
    "url": "",
    "rank": 75,
    "canvas": {
      "x": 1473.0,
      "y": 1177.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "076",
    "webp": "webp/076.webp",
    "label": "",
    "url": "",
    "rank": 76,
    "canvas": {
      "x": 1682.0,
      "y": 1180.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "077",
    "webp": "webp/077.webp",
    "label": "",
    "url": "",
    "rank": 77,
    "canvas": {
      "x": 1933.0,
      "y": 1147.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "078",
    "webp": "webp/078.webp",
    "label": "",
    "url": "",
    "rank": 78,
    "canvas": {
      "x": 2153.0,
      "y": 1141.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "079",
    "webp": "webp/079.webp",
    "label": "",
    "url": "",
    "rank": 79,
    "canvas": {
      "x": 2384.0,
      "y": 1145.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "080",
    "webp": "webp/080.webp",
    "label": "",
    "url": "",
    "rank": 80,
    "canvas": {
      "x": 2624.0,
      "y": 1159.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "081",
    "webp": "webp/081.webp",
    "label": "",
    "url": "",
    "rank": 81,
    "canvas": {
      "x": 2857.0,
      "y": 1150.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "082",
    "webp": "webp/082.webp",
    "label": "",
    "url": "",
    "rank": 82,
    "canvas": {
      "x": 3084.0,
      "y": 1151.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "083",
    "webp": "webp/083.webp",
    "label": "",
    "url": "",
    "rank": 83,
    "canvas": {
      "x": 3291.0,
      "y": 1151.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "084",
    "webp": "webp/084.webp",
    "label": "",
    "url": "",
    "rank": 84,
    "canvas": {
      "x": 3513.0,
      "y": 1143.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "085",
    "webp": "webp/085.webp",
    "label": "",
    "url": "",
    "rank": 85,
    "canvas": {
      "x": 3765.0,
      "y": 1169.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "086",
    "webp": "webp/086.webp",
    "label": "",
    "url": "",
    "rank": 86,
    "canvas": {
      "x": 95.0,
      "y": 1444.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "087",
    "webp": "webp/087.webp",
    "label": "",
    "url": "",
    "rank": 87,
    "canvas": {
      "x": 315.0,
      "y": 1418.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "088",
    "webp": "webp/088.webp",
    "label": "",
    "url": "",
    "rank": 88,
    "canvas": {
      "x": 533.0,
      "y": 1431.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "089",
    "webp": "webp/089.webp",
    "label": "",
    "url": "",
    "rank": 89,
    "canvas": {
      "x": 770.0,
      "y": 1445.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "090",
    "webp": "webp/090.webp",
    "label": "",
    "url": "",
    "rank": 90,
    "canvas": {
      "x": 985.0,
      "y": 1447.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "091",
    "webp": "webp/091.webp",
    "label": "",
    "url": "",
    "rank": 91,
    "canvas": {
      "x": 1219.0,
      "y": 1435.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "092",
    "webp": "webp/092.webp",
    "label": "",
    "url": "",
    "rank": 92,
    "canvas": {
      "x": 1449.0,
      "y": 1433.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "093",
    "webp": "webp/093.webp",
    "label": "",
    "url": "",
    "rank": 93,
    "canvas": {
      "x": 1692.0,
      "y": 1437.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "094",
    "webp": "webp/094.webp",
    "label": "",
    "url": "",
    "rank": 94,
    "canvas": {
      "x": 1926.0,
      "y": 1426.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "095",
    "webp": "webp/095.webp",
    "label": "",
    "url": "",
    "rank": 95,
    "canvas": {
      "x": 2154.0,
      "y": 1416.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "096",
    "webp": "webp/096.webp",
    "label": "",
    "url": "",
    "rank": 96,
    "canvas": {
      "x": 2360.0,
      "y": 1432.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "097",
    "webp": "webp/097.webp",
    "label": "",
    "url": "",
    "rank": 97,
    "canvas": {
      "x": 2629.0,
      "y": 1449.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "098",
    "webp": "webp/098.webp",
    "label": "",
    "url": "",
    "rank": 98,
    "canvas": {
      "x": 2855.0,
      "y": 1444.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "099",
    "webp": "webp/099.webp",
    "label": "",
    "url": "",
    "rank": 99,
    "canvas": {
      "x": 3083.0,
      "y": 1445.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "100",
    "webp": "webp/100.webp",
    "label": "",
    "url": "",
    "rank": 100,
    "canvas": {
      "x": 3320.0,
      "y": 1422.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "101",
    "webp": "webp/101.webp",
    "label": "",
    "url": "",
    "rank": 101,
    "canvas": {
      "x": 3540.0,
      "y": 1432.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "102",
    "webp": "webp/102.webp",
    "label": "",
    "url": "",
    "rank": 102,
    "canvas": {
      "x": 3763.0,
      "y": 1442.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "103",
    "webp": "webp/103.webp",
    "label": "",
    "url": "",
    "rank": 103,
    "canvas": {
      "x": 77.0,
      "y": 1704.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "104",
    "webp": "webp/104.webp",
    "label": "",
    "url": "",
    "rank": 104,
    "canvas": {
      "x": 318.0,
      "y": 1716.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "105",
    "webp": "webp/105.webp",
    "label": "",
    "url": "",
    "rank": 105,
    "canvas": {
      "x": 555.0,
      "y": 1698.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "106",
    "webp": "webp/106.webp",
    "label": "",
    "url": "",
    "rank": 106,
    "canvas": {
      "x": 776.0,
      "y": 1716.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "107",
    "webp": "webp/107.webp",
    "label": "",
    "url": "",
    "rank": 107,
    "canvas": {
      "x": 1000.0,
      "y": 1702.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "108",
    "webp": "webp/108.webp",
    "label": "",
    "url": "",
    "rank": 108,
    "canvas": {
      "x": 1237.0,
      "y": 1691.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "109",
    "webp": "webp/109.webp",
    "label": "",
    "url": "",
    "rank": 109,
    "canvas": {
      "x": 1472.0,
      "y": 1708.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "110",
    "webp": "webp/110.webp",
    "label": "",
    "url": "",
    "rank": 110,
    "canvas": {
      "x": 1695.0,
      "y": 1714.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "111",
    "webp": "webp/111.webp",
    "label": "",
    "url": "",
    "rank": 111,
    "canvas": {
      "x": 1914.0,
      "y": 1716.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "112",
    "webp": "webp/112.webp",
    "label": "",
    "url": "",
    "rank": 112,
    "canvas": {
      "x": 2159.0,
      "y": 1703.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "113",
    "webp": "webp/113.webp",
    "label": "",
    "url": "",
    "rank": 113,
    "canvas": {
      "x": 2392.0,
      "y": 1684.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "114",
    "webp": "webp/114.webp",
    "label": "",
    "url": "",
    "rank": 114,
    "canvas": {
      "x": 2591.0,
      "y": 1687.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "115",
    "webp": "webp/115.webp",
    "label": "",
    "url": "",
    "rank": 115,
    "canvas": {
      "x": 2844.0,
      "y": 1715.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "116",
    "webp": "webp/116.webp",
    "label": "",
    "url": "",
    "rank": 116,
    "canvas": {
      "x": 3064.0,
      "y": 1711.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "117",
    "webp": "webp/117.webp",
    "label": "",
    "url": "",
    "rank": 117,
    "canvas": {
      "x": 3305.0,
      "y": 1700.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "118",
    "webp": "webp/118.webp",
    "label": "",
    "url": "",
    "rank": 118,
    "canvas": {
      "x": 3521.0,
      "y": 1684.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "119",
    "webp": "webp/119.webp",
    "label": "",
    "url": "",
    "rank": 119,
    "canvas": {
      "x": 3774.0,
      "y": 1695.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "120",
    "webp": "webp/120.webp",
    "label": "",
    "url": "",
    "rank": 120,
    "canvas": {
      "x": 73.0,
      "y": 1950.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "121",
    "webp": "webp/121.webp",
    "label": "",
    "url": "",
    "rank": 121,
    "canvas": {
      "x": 308.0,
      "y": 1977.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "122",
    "webp": "webp/122.webp",
    "label": "",
    "url": "",
    "rank": 122,
    "canvas": {
      "x": 534.0,
      "y": 1960.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "123",
    "webp": "webp/123.webp",
    "label": "",
    "url": "",
    "rank": 123,
    "canvas": {
      "x": 790.0,
      "y": 1959.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "124",
    "webp": "webp/124.webp",
    "label": "",
    "url": "",
    "rank": 124,
    "canvas": {
      "x": 1011.0,
      "y": 1970.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "125",
    "webp": "webp/125.webp",
    "label": "",
    "url": "",
    "rank": 125,
    "canvas": {
      "x": 1218.0,
      "y": 1957.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "126",
    "webp": "webp/126.webp",
    "label": "",
    "url": "",
    "rank": 126,
    "canvas": {
      "x": 1471.0,
      "y": 1973.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "127",
    "webp": "webp/127.webp",
    "label": "",
    "url": "",
    "rank": 127,
    "canvas": {
      "x": 1706.0,
      "y": 1971.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "128",
    "webp": "webp/128.webp",
    "label": "",
    "url": "",
    "rank": 128,
    "canvas": {
      "x": 1918.0,
      "y": 1981.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "129",
    "webp": "webp/129.webp",
    "label": "",
    "url": "",
    "rank": 129,
    "canvas": {
      "x": 2141.0,
      "y": 1963.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "130",
    "webp": "webp/130.webp",
    "label": "",
    "url": "",
    "rank": 130,
    "canvas": {
      "x": 2396.0,
      "y": 1975.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "131",
    "webp": "webp/131.webp",
    "label": "",
    "url": "",
    "rank": 131,
    "canvas": {
      "x": 2615.0,
      "y": 1954.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "132",
    "webp": "webp/132.webp",
    "label": "",
    "url": "",
    "rank": 132,
    "canvas": {
      "x": 2853.0,
      "y": 1976.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "133",
    "webp": "webp/133.webp",
    "label": "",
    "url": "",
    "rank": 133,
    "canvas": {
      "x": 3051.0,
      "y": 1967.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "134",
    "webp": "webp/134.webp",
    "label": "",
    "url": "",
    "rank": 134,
    "canvas": {
      "x": 3291.0,
      "y": 1955.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "135",
    "webp": "webp/135.webp",
    "label": "",
    "url": "",
    "rank": 135,
    "canvas": {
      "x": 3512.0,
      "y": 1958.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "136",
    "webp": "webp/136.webp",
    "label": "",
    "url": "",
    "rank": 136,
    "canvas": {
      "x": 3760.0,
      "y": 1970.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "137",
    "webp": "webp/137.webp",
    "label": "",
    "url": "",
    "rank": 137,
    "canvas": {
      "x": 89.0,
      "y": 2250.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "138",
    "webp": "webp/138.webp",
    "label": "",
    "url": "",
    "rank": 138,
    "canvas": {
      "x": 294.0,
      "y": 2249.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "139",
    "webp": "webp/139.webp",
    "label": "",
    "url": "",
    "rank": 139,
    "canvas": {
      "x": 557.0,
      "y": 2230.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "140",
    "webp": "webp/140.webp",
    "label": "",
    "url": "",
    "rank": 140,
    "canvas": {
      "x": 776.0,
      "y": 2233.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "141",
    "webp": "webp/141.webp",
    "label": "",
    "url": "",
    "rank": 141,
    "canvas": {
      "x": 993.0,
      "y": 2228.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "142",
    "webp": "webp/142.webp",
    "label": "",
    "url": "",
    "rank": 142,
    "canvas": {
      "x": 1223.0,
      "y": 2225.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "143",
    "webp": "webp/143.webp",
    "label": "",
    "url": "",
    "rank": 143,
    "canvas": {
      "x": 1469.0,
      "y": 2229.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "144",
    "webp": "webp/144.webp",
    "label": "",
    "url": "",
    "rank": 144,
    "canvas": {
      "x": 1701.0,
      "y": 2259.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "145",
    "webp": "webp/145.webp",
    "label": "",
    "url": "",
    "rank": 145,
    "canvas": {
      "x": 1902.0,
      "y": 2220.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "146",
    "webp": "webp/146.webp",
    "label": "",
    "url": "",
    "rank": 146,
    "canvas": {
      "x": 2155.0,
      "y": 2247.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "147",
    "webp": "webp/147.webp",
    "label": "",
    "url": "",
    "rank": 147,
    "canvas": {
      "x": 2374.0,
      "y": 2236.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "148",
    "webp": "webp/148.webp",
    "label": "",
    "url": "",
    "rank": 148,
    "canvas": {
      "x": 2598.0,
      "y": 2226.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "149",
    "webp": "webp/149.webp",
    "label": "",
    "url": "",
    "rank": 149,
    "canvas": {
      "x": 2835.0,
      "y": 2226.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "150",
    "webp": "webp/150.webp",
    "label": "",
    "url": "",
    "rank": 150,
    "canvas": {
      "x": 3075.0,
      "y": 2255.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "151",
    "webp": "webp/151.webp",
    "label": "",
    "url": "",
    "rank": 151,
    "canvas": {
      "x": 3289.0,
      "y": 2241.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "152",
    "webp": "webp/152.webp",
    "label": "",
    "url": "",
    "rank": 152,
    "canvas": {
      "x": 3527.0,
      "y": 2249.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "153",
    "webp": "webp/153.webp",
    "label": "",
    "url": "",
    "rank": 153,
    "canvas": {
      "x": 3771.0,
      "y": 2238.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "154",
    "webp": "webp/154.webp",
    "label": "",
    "url": "",
    "rank": 154,
    "canvas": {
      "x": 85.0,
      "y": 2506.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "155",
    "webp": "webp/155.webp",
    "label": "",
    "url": "",
    "rank": 155,
    "canvas": {
      "x": 310.0,
      "y": 2496.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "156",
    "webp": "webp/156.webp",
    "label": "",
    "url": "",
    "rank": 156,
    "canvas": {
      "x": 550.0,
      "y": 2523.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "157",
    "webp": "webp/157.webp",
    "label": "",
    "url": "",
    "rank": 157,
    "canvas": {
      "x": 786.0,
      "y": 2491.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "158",
    "webp": "webp/158.webp",
    "label": "",
    "url": "",
    "rank": 158,
    "canvas": {
      "x": 990.0,
      "y": 2515.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "159",
    "webp": "webp/159.webp",
    "label": "",
    "url": "",
    "rank": 159,
    "canvas": {
      "x": 1219.0,
      "y": 2493.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "160",
    "webp": "webp/160.webp",
    "label": "",
    "url": "",
    "rank": 160,
    "canvas": {
      "x": 1443.0,
      "y": 2513.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "161",
    "webp": "webp/161.webp",
    "label": "",
    "url": "",
    "rank": 161,
    "canvas": {
      "x": 1677.0,
      "y": 2521.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "162",
    "webp": "webp/162.webp",
    "label": "",
    "url": "",
    "rank": 162,
    "canvas": {
      "x": 1919.0,
      "y": 2524.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "163",
    "webp": "webp/163.webp",
    "label": "",
    "url": "",
    "rank": 163,
    "canvas": {
      "x": 2131.0,
      "y": 2514.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "164",
    "webp": "webp/164.webp",
    "label": "",
    "url": "",
    "rank": 164,
    "canvas": {
      "x": 2391.0,
      "y": 2505.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "165",
    "webp": "webp/165.webp",
    "label": "",
    "url": "",
    "rank": 165,
    "canvas": {
      "x": 2595.0,
      "y": 2500.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "166",
    "webp": "webp/166.webp",
    "label": "",
    "url": "",
    "rank": 166,
    "canvas": {
      "x": 2835.0,
      "y": 2524.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "167",
    "webp": "webp/167.webp",
    "label": "",
    "url": "",
    "rank": 167,
    "canvas": {
      "x": 3069.0,
      "y": 2520.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "168",
    "webp": "webp/168.webp",
    "label": "",
    "url": "",
    "rank": 168,
    "canvas": {
      "x": 3280.0,
      "y": 2490.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "169",
    "webp": "webp/169.webp",
    "label": "",
    "url": "",
    "rank": 169,
    "canvas": {
      "x": 3511.0,
      "y": 2497.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "170",
    "webp": "webp/170.webp",
    "label": "",
    "url": "",
    "rank": 170,
    "canvas": {
      "x": 3753.0,
      "y": 2518.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "171",
    "webp": "webp/171.webp",
    "label": "",
    "url": "",
    "rank": 171,
    "canvas": {
      "x": 92.0,
      "y": 2796.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "172",
    "webp": "webp/172.webp",
    "label": "",
    "url": "",
    "rank": 172,
    "canvas": {
      "x": 298.0,
      "y": 2770.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "173",
    "webp": "webp/173.webp",
    "label": "",
    "url": "",
    "rank": 173,
    "canvas": {
      "x": 524.0,
      "y": 2789.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "174",
    "webp": "webp/174.webp",
    "label": "",
    "url": "",
    "rank": 174,
    "canvas": {
      "x": 764.0,
      "y": 2771.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "175",
    "webp": "webp/175.webp",
    "label": "",
    "url": "",
    "rank": 175,
    "canvas": {
      "x": 988.0,
      "y": 2797.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "176",
    "webp": "webp/176.webp",
    "label": "",
    "url": "",
    "rank": 176,
    "canvas": {
      "x": 1222.0,
      "y": 2772.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "177",
    "webp": "webp/177.webp",
    "label": "",
    "url": "",
    "rank": 177,
    "canvas": {
      "x": 1448.0,
      "y": 2795.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "178",
    "webp": "webp/178.webp",
    "label": "",
    "url": "",
    "rank": 178,
    "canvas": {
      "x": 1699.0,
      "y": 2765.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "179",
    "webp": "webp/179.webp",
    "label": "",
    "url": "",
    "rank": 179,
    "canvas": {
      "x": 1935.0,
      "y": 2782.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "180",
    "webp": "webp/180.webp",
    "label": "",
    "url": "",
    "rank": 180,
    "canvas": {
      "x": 2156.0,
      "y": 2795.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "181",
    "webp": "webp/181.webp",
    "label": "",
    "url": "",
    "rank": 181,
    "canvas": {
      "x": 2372.0,
      "y": 2777.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "182",
    "webp": "webp/182.webp",
    "label": "",
    "url": "",
    "rank": 182,
    "canvas": {
      "x": 2622.0,
      "y": 2772.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "183",
    "webp": "webp/183.webp",
    "label": "",
    "url": "",
    "rank": 183,
    "canvas": {
      "x": 2828.0,
      "y": 2773.0,
      "rot": 0.0,
      "scale": 1.0
    }
  },
  {
    "id": "184",
    "webp": "webp/184.webp",
    "label": "",
    "url": "",
    "rank": 184,
    "canvas": {
      "x": 3050.0,
      "y": 2782.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "185",
    "webp": "webp/185.webp",
    "label": "",
    "url": "",
    "rank": 185,
    "canvas": {
      "x": 3281.0,
      "y": 2765.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "186",
    "webp": "webp/186.webp",
    "label": "",
    "url": "",
    "rank": 186,
    "canvas": {
      "x": 3535.0,
      "y": 2776.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "187",
    "webp": "webp/187.webp",
    "label": "",
    "url": "",
    "rank": 187,
    "canvas": {
      "x": 3750.0,
      "y": 2793.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "188",
    "webp": "webp/188.webp",
    "label": "",
    "url": "",
    "rank": 188,
    "canvas": {
      "x": 79.0,
      "y": 3049.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "189",
    "webp": "webp/189.webp",
    "label": "",
    "url": "",
    "rank": 189,
    "canvas": {
      "x": 300.0,
      "y": 3064.0,
      "rot": -1.0,
      "scale": 1.0
    }
  },
  {
    "id": "190",
    "webp": "webp/190.webp",
    "label": "",
    "url": "",
    "rank": 190,
    "canvas": {
      "x": 560.0,
      "y": 3042.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "191",
    "webp": "webp/191.webp",
    "label": "",
    "url": "",
    "rank": 191,
    "canvas": {
      "x": 776.0,
      "y": 3048.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "192",
    "webp": "webp/192.webp",
    "label": "",
    "url": "",
    "rank": 192,
    "canvas": {
      "x": 989.0,
      "y": 3059.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "193",
    "webp": "webp/193.webp",
    "label": "",
    "url": "",
    "rank": 193,
    "canvas": {
      "x": 1219.0,
      "y": 3053.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "194",
    "webp": "webp/194.webp",
    "label": "",
    "url": "",
    "rank": 194,
    "canvas": {
      "x": 1454.0,
      "y": 3060.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "195",
    "webp": "webp/195.webp",
    "label": "",
    "url": "",
    "rank": 195,
    "canvas": {
      "x": 1687.0,
      "y": 3056.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "196",
    "webp": "webp/196.webp",
    "label": "",
    "url": "",
    "rank": 196,
    "canvas": {
      "x": 1908.0,
      "y": 3030.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "197",
    "webp": "webp/197.webp",
    "label": "",
    "url": "",
    "rank": 197,
    "canvas": {
      "x": 2134.0,
      "y": 3054.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "198",
    "webp": "webp/198.webp",
    "label": "",
    "url": "",
    "rank": 198,
    "canvas": {
      "x": 2394.0,
      "y": 3032.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "199",
    "webp": "webp/199.webp",
    "label": "",
    "url": "",
    "rank": 199,
    "canvas": {
      "x": 2597.0,
      "y": 3038.0,
      "rot": -8.0,
      "scale": 1.0
    }
  },
  {
    "id": "200",
    "webp": "webp/200.webp",
    "label": "",
    "url": "",
    "rank": 200,
    "canvas": {
      "x": 2832.0,
      "y": 3034.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "201",
    "webp": "webp/201.webp",
    "label": "",
    "url": "",
    "rank": 201,
    "canvas": {
      "x": 3086.0,
      "y": 3067.0,
      "rot": -6.0,
      "scale": 1.0
    }
  },
  {
    "id": "202",
    "webp": "webp/202.webp",
    "label": "",
    "url": "",
    "rank": 202,
    "canvas": {
      "x": 3307.0,
      "y": 3044.0,
      "rot": 5.0,
      "scale": 1.0
    }
  },
  {
    "id": "203",
    "webp": "webp/203.webp",
    "label": "",
    "url": "",
    "rank": 203,
    "canvas": {
      "x": 3543.0,
      "y": 3064.0,
      "rot": -3.0,
      "scale": 1.0
    }
  },
  {
    "id": "204",
    "webp": "webp/204.webp",
    "label": "",
    "url": "",
    "rank": 204,
    "canvas": {
      "x": 3777.0,
      "y": 3038.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "205",
    "webp": "webp/205.webp",
    "label": "",
    "url": "",
    "rank": 205,
    "canvas": {
      "x": 66.0,
      "y": 3310.0,
      "rot": -2.0,
      "scale": 1.0
    }
  },
  {
    "id": "206",
    "webp": "webp/206.webp",
    "label": "",
    "url": "",
    "rank": 206,
    "canvas": {
      "x": 301.0,
      "y": 3309.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "207",
    "webp": "webp/207.webp",
    "label": "",
    "url": "",
    "rank": 207,
    "canvas": {
      "x": 532.0,
      "y": 3303.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "208",
    "webp": "webp/208.webp",
    "label": "",
    "url": "",
    "rank": 208,
    "canvas": {
      "x": 781.0,
      "y": 3335.0,
      "rot": 6.0,
      "scale": 1.0
    }
  },
  {
    "id": "209",
    "webp": "webp/209.webp",
    "label": "",
    "url": "",
    "rank": 209,
    "canvas": {
      "x": 998.0,
      "y": 3321.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "210",
    "webp": "webp/210.webp",
    "label": "",
    "url": "",
    "rank": 210,
    "canvas": {
      "x": 1246.0,
      "y": 3313.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "211",
    "webp": "webp/211.webp",
    "label": "",
    "url": "",
    "rank": 211,
    "canvas": {
      "x": 1459.0,
      "y": 3303.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "212",
    "webp": "webp/212.webp",
    "label": "",
    "url": "",
    "rank": 212,
    "canvas": {
      "x": 1673.0,
      "y": 3331.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "213",
    "webp": "webp/213.webp",
    "label": "",
    "url": "",
    "rank": 213,
    "canvas": {
      "x": 1922.0,
      "y": 3324.0,
      "rot": 3.0,
      "scale": 1.0
    }
  },
  {
    "id": "214",
    "webp": "webp/214.webp",
    "label": "",
    "url": "",
    "rank": 214,
    "canvas": {
      "x": 2168.0,
      "y": 3300.0,
      "rot": -4.0,
      "scale": 1.0
    }
  },
  {
    "id": "215",
    "webp": "webp/215.webp",
    "label": "",
    "url": "",
    "rank": 215,
    "canvas": {
      "x": 2378.0,
      "y": 3300.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "216",
    "webp": "webp/216.webp",
    "label": "",
    "url": "",
    "rank": 216,
    "canvas": {
      "x": 2597.0,
      "y": 3302.0,
      "rot": -7.0,
      "scale": 1.0
    }
  },
  {
    "id": "217",
    "webp": "webp/217.webp",
    "label": "",
    "url": "",
    "rank": 217,
    "canvas": {
      "x": 2859.0,
      "y": 3335.0,
      "rot": 4.0,
      "scale": 1.0
    }
  },
  {
    "id": "218",
    "webp": "webp/218.webp",
    "label": "",
    "url": "",
    "rank": 218,
    "canvas": {
      "x": 3067.0,
      "y": 3303.0,
      "rot": 1.0,
      "scale": 1.0
    }
  },
  {
    "id": "219",
    "webp": "webp/219.webp",
    "label": "",
    "url": "",
    "rank": 219,
    "canvas": {
      "x": 3283.0,
      "y": 3318.0,
      "rot": -5.0,
      "scale": 1.0
    }
  },
  {
    "id": "220",
    "webp": "webp/220.webp",
    "label": "",
    "url": "",
    "rank": 220,
    "canvas": {
      "x": 3535.0,
      "y": 3324.0,
      "rot": 2.0,
      "scale": 1.0
    }
  },
  {
    "id": "221",
    "webp": "webp/221.webp",
    "label": "",
    "url": "",
    "rank": 221,
    "canvas": {
      "x": 3777.0,
      "y": 3340.0,
      "rot": 7.0,
      "scale": 1.0
    }
  },
  {
    "id": "222",
    "webp": "webp/222.webp",
    "label": "",
    "url": "",
    "rank": 222,
    "canvas": {
      "x": 90.0,
      "y": 3587.0,
      "rot": 8.0,
      "scale": 1.0
    }
  },
  {
    "id": "223",
    "webp": "webp/223.webp",
    "label": "",
    "url": "",
    "rank": 223,
    "canvas": {
      "x": 329.0,
      "y": 3605.0,
      "rot": 5.0,
      "scale": 1.0
    }
  }
];
