#!/usr/bin/env python3
"""Sync sticker WebPs and data.js from the PNG files on disk.

Usage (from repo root):
    python tools/build-webp.py
    python tools/build-webp.py --drop 212

Existing webp/{id}.webp files are kept unless the PNG is newer.
Stickers removed from the folder are dropped from data.js. Labels, ranks,
and canvas positions are preserved for IDs that still exist.

If you deleted a PNG and renamed later files to close the gap, pass
--drop <id> so metadata shifts with the files (old 213 becomes 212, etc.).

Requires Pillow:  python -m pip install Pillow
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
WEBP_DIR = ROOT / "webp"
DATA_JS = ROOT / "data.js"
MAX_EDGE = 1200
WEBP_QUALITY = 80
WEBP_METHOD = 4


def sticker_id(path: Path) -> str:
    return path.stem


def pad_id(value: int) -> str:
    return f"{value:03d}"


def parse_id(sid: str) -> int | None:
    try:
        return int(sid)
    except ValueError:
        return None


def canvas_layout(sid: str, index: int, total: int) -> dict:
    cols = max(1, math.ceil(math.sqrt(total * 1.2)))
    col = index % cols
    row = index // cols
    digest = hashlib.md5(sid.encode("utf-8")).digest()
    h = int.from_bytes(digest[:4], "little")
    return {
        "x": 80 + col * 230 + (h % 41) - 20,
        "y": 80 + row * 270 + ((h >> 8) % 41) - 20,
        "rot": ((h >> 16) % 17) - 8,
        "scale": 1,
    }


def extract_js_assign(source: str, name: str):
    match = re.search(rf"window\.{name}\s*=\s*", source)
    if not match:
        return None
    decoder = json.JSONDecoder()
    try:
        value, _ = decoder.raw_decode(source[match.end() :])
    except json.JSONDecodeError:
        return None
    return value


def load_existing(path: Path) -> tuple[dict, dict]:
    if not path.exists():
        return {}, {"bookCols": 2, "bookRows": 3}
    text = path.read_text(encoding="utf-8")
    stickers = extract_js_assign(text, "STICKERS") or []
    settings = extract_js_assign(text, "SETTINGS") or {}
    by_id = {str(item.get("id")): item for item in stickers if item.get("id")}
    settings.setdefault("bookCols", 2)
    settings.setdefault("bookRows", 3)
    return by_id, settings


def write_data_js(path: Path, settings: dict, stickers: list[dict]) -> None:
    payload = (
        "/* Generated by tools/build-webp.py. Editor export may replace this file. */\n"
        f"window.SETTINGS = {json.dumps(settings, indent=2)};\n\n"
        f"window.STICKERS = {json.dumps(stickers, indent=2)};\n"
    )
    path.write_text(payload, encoding="utf-8")


def convert_png(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as img:
        frame = img.convert("RGBA")
        frame.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)
        frame.save(
            dest,
            format="WEBP",
            quality=WEBP_QUALITY,
            method=WEBP_METHOD,
            exact=True,
        )


def metadata_for(sid: str, existing: dict, drop_id: int | None) -> dict:
    if drop_id is None:
        return existing.get(sid, {})
    numeric = parse_id(sid)
    if numeric is None or numeric < drop_id:
        return existing.get(sid, {})
    return existing.get(pad_id(numeric + 1), {})


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh webp/ and data.js from PNG files.")
    parser.add_argument(
        "--drop",
        metavar="ID",
        help="Deleted sticker id after files were renamed to close the gap (example: 212)",
    )
    args = parser.parse_args()
    drop_id = parse_id(str(args.drop)) if args.drop else None
    if args.drop and drop_id is None:
        print(f"Invalid --drop id: {args.drop}", file=sys.stderr)
        return 1

    pngs = sorted(ROOT.glob("*.png"), key=lambda p: p.name.lower())
    if not pngs:
        print(f"No PNG files found in {ROOT}", file=sys.stderr)
        return 1

    existing, settings = load_existing(DATA_JS)
    WEBP_DIR.mkdir(parents=True, exist_ok=True)

    keep_ids = {sticker_id(png) for png in pngs}
    stickers: list[dict] = []
    converted = 0
    skipped = 0
    total = len(pngs)

    for index, png in enumerate(pngs):
        sid = sticker_id(png)
        dest = WEBP_DIR / f"{sid}.webp"
        numeric = parse_id(sid)
        shifted = drop_id is not None and numeric is not None and numeric >= drop_id
        needs_write = (
            shifted
            or not dest.exists()
            or dest.stat().st_mtime < png.stat().st_mtime
        )
        if needs_write:
            convert_png(png, dest)
            converted += 1
            print(f"[{index + 1}/{total}] wrote {dest.relative_to(ROOT)}")
        else:
            skipped += 1

        prev = metadata_for(sid, existing, drop_id)
        canvas = prev.get("canvas") or canvas_layout(sid, index, total)
        rank = prev.get("rank")
        if not isinstance(rank, int) or rank < 1:
            rank = index + 1
        stickers.append(
            {
                "id": sid,
                "webp": f"webp/{sid}.webp",
                "label": prev.get("label") or "",
                "url": prev.get("url") or "",
                "rank": rank,
                "canvas": {
                    "x": float(canvas.get("x", 0)),
                    "y": float(canvas.get("y", 0)),
                    "rot": float(canvas.get("rot", 0)),
                    "scale": float(canvas.get("scale", 1) or 1),
                },
            }
        )

    removed = sorted(set(existing) - keep_ids)
    orphans = 0
    for webp in WEBP_DIR.glob("*.webp"):
        if sticker_id(webp) not in keep_ids:
            webp.unlink()
            orphans += 1
            print(f"removed orphan {webp.relative_to(ROOT)}")

    stickers.sort(key=lambda item: (item["rank"], item["id"]))
    for index, item in enumerate(stickers, start=1):
        item["rank"] = index

    write_data_js(DATA_JS, settings, stickers)
    print(
        f"Done. {converted} converted, {skipped} webp kept, "
        f"{len(removed)} ids dropped from data.js, {orphans} orphan webp removed, "
        f"{len(stickers)} stickers in {DATA_JS.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
